spring:
  datasource:
    url: jdbc:mysql://feelow.cvqqak8scuix.ap-northeast-2.rds.amazonaws.com:3306/feelow?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: admin
    password: ${rds_pwd}
    driver-class-name: com.mysql.cj.jdbc.Driver

    jackson:
        serialization:
          write-dates-as-timestamps: false
          write-date-timestamps-as-nanoseconds: false
          indent-output: true
          write-char-array-as-string: true
          fail-on-empty-beans: false

  jpa:
    hibernate:
        ddl-auto: update
    show-sql: true

  profiles:
    include: real-db

  session:
    store-type: jdbc

  jackson:
    serialization:
      fail-on-empty-beans: false

server:
  address: 0.0.0.0
  port: 8080

logging:
  level:
    org:
      springframework.web : DEBUG
      springframework.security : DEBUG
    com:
      fasterxml.jackson : DEBUG

cloud:
  aws:
    s3:
      bucket: feelow
    credentials:
      access-key: AKIARDQVELZJVHXDAXGG
      secret-key: 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
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

